import 'fake-indexeddb/auto';
import test from 'node:test';
import assert from 'node:assert/strict';
import { IDBObjectStore } from 'fake-indexeddb';
import { addImage, getImage, listImages, updateImage, deleteImage, deleteDesignFamily, saveRestyleVersion, getRestyleRecord } from '../src/storage.js';
import { resultFixture } from './restyle-fixtures.js';

const blob = (text) => new Blob([text], { type: 'image/png' });
async function fixture() {
  const source = await addImage({ roomId: 'kuche', blob: blob('original'), title: 'Kitchen', width: 100, height: 80 });
  return { source, inspiration: new File(['inspiration'], 'style.png', { type: 'image/png' }), result: resultFixture(crypto.randomUUID()), rendered: { blob: blob('render'), width: 100, height: 80 } };
}

test('version and provenance persist atomically without modifying the source', async () => {
  const data = await fixture();
  const image = await saveRestyleVersion(data);
  assert.notEqual(image.id, data.source.id);
  assert.equal(image.parentImageId, data.source.id); assert.equal(image.rootImageId, data.source.id);
  assert.deepEqual(await getImage(data.source.id), data.source);
  assert.equal((await listImages('bad')).length, 0);
  const record = await getRestyleRecord(data.result.requestId);
  assert.equal(await record.source.blob.text(), 'original');
  assert.equal(await record.inspiration.blob.text(), 'inspiration');
  const next = await saveRestyleVersion({ ...data, source: image, result: resultFixture(crypto.randomUUID()) });
  assert.equal(next.parentImageId, image.id); assert.equal(next.rootImageId, data.source.id);
  const connection = await import('../src/storage.js?restyle-reopen');
  assert.equal((await connection.getImage(next.id)).restyleId, next.restyleId);
});

test('source snapshots survive replacement and deletion; generated bytes stay immutable', async () => {
  const data = await fixture(); const image = await saveRestyleVersion(data);
  await updateImage(data.source.id, { blob: blob('replaced') });
  await deleteImage(data.source.id);
  assert.equal(await (await getRestyleRecord(data.result.requestId)).source.blob.text(), 'original');
  await assert.rejects(updateImage(image.id, { blob: blob('replacement') }), /cannot be replaced/);
  await updateImage(image.id, { title: 'Renamed', parentImageId: 'invalid' });
  assert.equal((await getImage(image.id)).parentImageId, data.source.id);
  await deleteImage(image.id);
  assert.equal(await getRestyleRecord(data.result.requestId), undefined);
});

test('deleting a design family removes every retained version and provenance record', async () => {
  const data = await fixture();
  const first = await saveRestyleVersion(data);
  const secondResult = resultFixture(crypto.randomUUID());
  const second = await saveRestyleVersion({ ...data, source: first, result: secondResult });
  const other = await fixture();
  await deleteImage(data.source.id);

  await deleteDesignFamily(data.source.id);

  assert.equal(await getImage(first.id), undefined);
  assert.equal(await getImage(second.id), undefined);
  assert.equal(await getRestyleRecord(data.result.requestId), undefined);
  assert.equal(await getRestyleRecord(secondResult.requestId), undefined);
  assert.equal((await getImage(other.source.id)).id, other.source.id);
});

test('concurrent completion is idempotent by request ID', async () => {
  const data = await fixture();
  const [first, second] = await Promise.all([saveRestyleVersion(data), saveRestyleVersion(data)]);
  assert.equal(first.id, second.id);
  assert.equal((await listImages()).filter((item) => item.restyleId === data.result.requestId).length, 1);
});

test('mock versions retain mode provenance, source links and distinct download filenames', async () => {
  const data = await fixture(); data.result.mode = 'mock';
  data.result.models = { reasoning: 'local-mock-style-v1', image: 'local-mock-image-v1' };
  const saved = await saveRestyleVersion(data);
  assert.equal(saved.mode, 'mock'); assert.match(saved.filename, /^mock-restyle-/);
  assert.equal(saved.parentImageId, data.source.id);
  const record = await getRestyleRecord(saved.restyleId);
  assert.equal(record.mode, 'mock'); assert.equal(record.models.image, 'local-mock-image-v1');
  assert.equal(await record.source.blob.text(), 'original');
  assert.equal((await saveRestyleVersion(data)).id, saved.id);
});

test('refinements save their request without requiring a second inspiration image', async () => {
  const data = await fixture(); const first = await saveRestyleVersion(data);
  const result = { ...resultFixture(crypto.randomUUID()), operation: 'refine', instruction: 'Replace the sofa with a curved cream sofa.' };
  const saved = await saveRestyleVersion({ ...data, source: first, inspiration: null, result });
  const record = await getRestyleRecord(saved.restyleId);
  assert.equal(saved.parentImageId, first.id); assert.equal(saved.rootImageId, data.source.id);
  assert.equal(saved.restyleOperation, 'refine'); assert.equal(saved.restyleInstruction, result.instruction);
  assert.equal(record.operation, 'refine'); assert.equal(record.instruction, result.instruction); assert.equal(record.inspiration, null);
});

test('aborted provenance write leaves no partial image and can retry with the same result', async () => {
  const data = await fixture(); const previous = IDBObjectStore.prototype.add;
  IDBObjectStore.prototype.add = function (...args) {
    const request = previous.apply(this, args);
    if (this.name === 'restyles') this.transaction.abort();
    return request;
  };
  try { await assert.rejects(saveRestyleVersion(data)); }
  finally { IDBObjectStore.prototype.add = previous; }
  assert.equal((await listImages()).some((image) => image.restyleId === data.result.requestId), false);
  assert.equal(await getRestyleRecord(data.result.requestId), undefined);
  const saved = await saveRestyleVersion(data);
  assert.equal(saved.restyleId, data.result.requestId);
});
